services:
    mroca_request_log.reponse_logger:
        class: Mroca\RequestLogBundle\Service\ResponseLogger
        arguments:
            - '%mroca_request_log.mocks_dir%'
            - '%mroca_request_log.hash_query_params%'
            - '%mroca_request_log.use_indexed_associative_array%'

    mroca_request_log.reponse_log_listener:
        class: Mroca\RequestLogBundle\EventListener\ResponseLogSubscriber
        arguments:
            - '@mroca_request_log.reponse_logger'
        tags:
            - { name: kernel.event_subscriber }

    mroca_request_log.command.clear_request_logs:
        class: Mroca\RequestLogBundle\Command\ClearRequestLogsCommand
        arguments:
            - '@mroca_request_log.reponse_logger'
        tags:
            -  { name: console.command }

    mroca_request_log.command.dump_request_logs:
        class: Mroca\RequestLogBundle\Command\DumpRequestLogsCommand
        arguments:
            - '@mroca_request_log.reponse_logger'
        tags:
            -  { name: console.command }
